version: '3.8'

services:
  todo:
    image: postgres:13
    container_name: todo_table
    environment:
      POSTGRES_USER: $(POSTGRES_USER)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - todo_data:/var/lib/postgresql/data # データの永続化(Postgresqlが保持するデータをtodo_dataという名前付きVolumeで永続的に保存している)
      - ./src/app/infrastructure/database/createtable.sql:/docker-entrypoint-initdb.d/createtable.sql # SQLファイルのマウント

# 名前付きボリューム
volumes:
  todo_data:
